### ISSUE TITLE
Can you add an option of autotranslate using google API?

### ISSUE THREAD

**Issue by Xelwon** [HakanL/resxtranslator#13]
Now when you add a new language have the option to copy (default values) strings.
The Idea was in that point send one by one all string to the google translator api and put the result in your new language. Using that initial translation as base.

That ease translation of applications with too many strings to translate.

Here is a quicky and easy method to translate a string.

https://developers.google.com/api-client-library/dotnet/apis/translate/v2

**Comment by Klocman** [comment]
The API is free for 60 days, then you have to pay $20 per million characters.

**Comment by Xelwon** [comment]
Then use direct HTTP google translator Freely.

Something like this

https://weblog.west-wind.com/posts/2011/aug/06/translating-with-google-translate-without-api-and-c-code

**Comment by Klocman** [comment]
Interesting, I will look into implementing this!

**Comment by Klocman** [comment]
Looks like Google blocked this method. Trying it results in a temporary IP block.

**Comment by Klocman** [comment]
I found a service that might potentially work for this: https://mymemory.translated.net/doc/spec.php https://mymemory.translated.net/doc/usagelimits.php

**Comment by enagora** [comment]
I added a brach with Auto-translate-and-new-features. It does that. As Klockman said, google block ip temporary when exceed a number of translations. 

You will see in button bar that application remains retrying while translations are not finished. 

You can use this branch or get my repo https://github.com/enagora/resxtranslator/ with these changes applied
