### ISSUE TITLE
Can you add an option for specific culture codes that use 3 letters?

### ISSUE THREAD

**Issue by davidmarkscott** [HakanL/resxtranslator#18]
At the moment the software (and the standards it is based on), limit the specific culture code to two letters.

For example, if the code is "fr-CA" (French - Canada), the "CA" part of the code must be two letters.

This is an issue if you want to use "zh-CHT" or "zh-CHS" - the codes for traditional and simplified Chinese.

If you load a directory with these files, it will be loaded as 2 different items.
One will have two translations (invariant and "fr-CA"), and the other file will have only "zh-CHS"

* test.resx
* test.fr-CA.resx
* test.zh-CHS.resx

Extending this to allow three characters would solve this issue.

A better longer term fix would be to also allow 4 characters (eg. "zh-Hans").
A harder problem is to deal with 3 elements in the code (eg. "sr-SP-Cyrl").

**Comment by Klocman** [comment]
It was an issue in the resource loading logic. All unusual language codes should work now. Do you want me to compile you the newest version or can you do it yourself?

By the way:
> Applications that target Windows Vista and later should use zh-Hans instead of zh-CHS and zh-Hant instead of zh-CHT. zh-Hans and zh-Hant represent the current standard and should be used unless you have a reason for using the older names.
> Note also that the results of the example may differ on an installation of Taiwanese Windows, where the input of a Chinese (Traditional) neutral culture (zh, zh-CHT, or zh-Hant) will return zh-TW.

[Source](https://msdn.microsoft.com/en-us/library/system.globalization.cultureinfo.createspecificculture(v=vs.110).aspx)

**Comment by davidmarkscott** [comment]
Can you compile it for me? I've only got VS2013. I believe I need VS2015 or newer to compile this project. Is that correct?

**Comment by Klocman** [comment]
I only tested it on VS2015, older might work as well. Here's a compiled verison:
[Release.zip](https://github.com/HakanL/resxtranslator/files/1090939/Release.zip)

**Comment by davidmarkscott** [comment]
Works great! Thanks
