### ISSUE TITLE
Adding new entry using the cell editor doesn't work

### ISSUE THREAD

**Issue by SeriousMartin** [HakanL/resxtranslator#20]
To reproduce:

1. Double click the key column in the empty row. In the cell editor enter a name for the key and accept
2. Double click the value column. In the cell editor enter some text and accept

Problems:
- When I now click on another field, the values disappear from the empty row. When I click into the row again, the values reappear.
- When I save the row is not saved
- When I single click the value cell and type something a new empty row finally appears. But when I now click on another field, I get a "System.Data.NoNullAllowedException for the Key

**Comment by Klocman** [comment]
This is a bug, it's supposed to be impossible to add rows from the list itself (there's no code behind for it).
