### ISSUE TITLE
Saving Problem

### ISSUE THREAD

**Issue by Joooki** [HakanL/resxtranslator#21]
Seems to me that i always have to click into another field first, after making changes in one field that I want to save by pressing crtl+s

**Comment by Klocman** [comment]
Do you mean when editing a cell directly (not in editor window)? If yes, you need to finish editing by selecting something else before changes are saved.

**Comment by Joooki** [comment]
Yes, always having to click into another field before i can press crtl+s is kind of a bug I thought. Because I often ended up with my changes not applied+saved before I realized this. But I guess one could life on with this detail, still i comes along a bit unhandy.

**Comment by Klocman** [comment]
Fixed, now you can ctrl+s when editing a cell and the value will be saved properly (without exiting edit mode).

**Comment by Joooki** [comment]
Cool! Thanks!
