### ISSUE TITLE
Exporting into zip file

### ISSUE THREAD

**Issue by Scippy** [HakanL/resxtranslator#25]
It could be a great improvment if will be added the features to export into zip file all added resurces file or export in other folder.
I use this tool for modules website translator and without this feature I need to pick one to one every resx file created to add in others websites.

**Comment by Klocman** [comment]
Do you mean compress all of the opened resources into a single archive? In that case why not just compress the directory?

Or, do you mean only compress the current resource and its languages?

**Comment by Scippy** [comment]
Yes, all opened resources into a single archivie with also directory structure. This because in some web module project the resources are distributed into different folders and now for copy resx files into other web project using same module I must pick the resx files one at one and copy everyone in the right folder. This folder contains other personalized files like css or theme in addiction at resx files, for this reason I can’t directly zip them and move in other similar project or distribute them as language package. Hope I’ve explained better now, and thanks for fast reply.

**Comment by Klocman** [comment]
Done, you can compile the source to get the functionality.

**Comment by Scippy** [comment]
Yes great! I've tried it and it is exactly what I need!
Thanks!
