### ISSUE TITLE
Configure the translated extension

### ISSUE THREAD

**Issue by Scippy** [HakanL/resxtranslator#26]
In my .net cms the translated resource have different extension from that generated by resxtranslator. For example to add the Italian language resource I must use the esxtension **.it-IT.resx** instead the **.it.resx** 
So I need to rename all language resources files generated by resxtranslator.
I suggest you to make configurable the extension generated by resxtranslator.
Regards

**Comment by Klocman** [comment]
it-IT is a valid culture, you don't have to change it manually. Just add the 'it-IT' language instead of the neutral 'it'. (you have to uncheck "Only neutral" for the specific culture to show up)
