### ISSUE TITLE
Chinese char incorrect after pasted from clipboard

### ISSUE THREAD

**Issue by ABSoftAsia** [HakanL/resxtranslator#27]
Hi, HakanL
Appreciate your work first all !
As I mentioned as title, please refer this picture
[https://www.dropbox.com/s/n5u6tpbcckl4pw8/paste-error.jpg?dl=0](https://www.dropbox.com/s/n5u6tpbcckl4pw8/paste-error.jpg?dl=0)

Thank you very mush.

**Comment by Klocman** [comment]
Hello!

I just checked and pasting works correctly if you edit a cell (double click it). It only gives ?? when pasting into a selected, but not editing cell, if that makes any sense.

**Comment by ABSoftAsia** [comment]
Hello, HakanL
In Cell Editor window(shows after double click it), both works fine no matter when input using Chinese input method or paste from clipboard.

Edit direct in cell of grid,
input using Chinese input method => works correctly,
but incorrectly after pasted from clipboard which I copy it into clipboard from other place earlier.
(I hope my English grammar is right that shows which I want to say.)

But no matter, after I study your source code, I find this:
Controls\ResourceGrid.cs > PasteFromClipboard()
  _var rowData = Regex.Split(dataObject.GetData(DataFormats.**Text**..._
change to
  _var rowData = Regex.Split(dataObject.GetData(DataFormats.**UnicodeText**..._
will fix this issue.

Thanks a million for your kind to share this wonderful tool !!

**Comment by Klocman** [comment]
Thank you for the help, I fixed this issue, and issue with pasting into the last row. To get the fix you can compile the source or download compiled version here: [Debug.zip](https://github.com/HakanL/resxtranslator/files/1609065/Debug.zip)
