### ISSUE TITLE
Cannot remove comment from the reference resource file

### ISSUE THREAD

**Issue by laperouse** [HakanL/resxtranslator#28]
If I had a comment in my reference file and in all translated file, and I removed the comment in my reference file (outside of resxtranlator), then when i edit the translation value in resxtranslator and I save, the comment from the translated file is copied back to the reference file, which I don't want.
The comment should only be from the reference file and as such should propagate to the translated files and not backward.

**Comment by Klocman** [comment]
What about an option to only store the comment in the main file? If there is no main file I guess it would just fall back to how things work now.

**Comment by laperouse** [comment]
OK, to only read and store comment in the main file.

**Comment by Klocman** [comment]
Can you check if this build works for you? There is a new option under the settings menu that you need to disable. 
[Debug.zip](https://github.com/HakanL/resxtranslator/files/1861194/Debug.zip)

**Comment by Klocman** [comment]
Glad to hear it works, let me know if you have any other suggestions!
