### ISSUE TITLE
Indicator for unsaved files

### ISSUE THREAD

**Issue by jochembroekhoff** [HakanL/resxtranslator#29]
It would be great if the editor would display something like an asterisk to indicate that there are unsaved changes.

**Comment by Klocman** [comment]
Here you go, done. Can you build the new version by yourself?

**Comment by jochembroekhoff** [comment]
Great! Sure, that's no problem. I can build it for myself.

**Comment by jochembroekhoff** [comment]
Well, it seemed to be working.
At this moment, the indicator only appears in the title bar. I actually expected to see it in the tabs too.

**Comment by Klocman** [comment]
At the moment you can open only one tab and there isn't an easy way to add mark based on specific resources so I decided to not do this for now.

**Comment by jochembroekhoff** [comment]
No problem.
