### ISSUE TITLE
Search Function

### ISSUE THREAD

**Issue by Joooki** [HakanL/resxtranslator#34]
I work a lot with resx translator and I'd love to have a search function. Very basic idea: a button to jump to the next entry of a keyword in the open file. Would be awesome because our translation files are usually very complex and you have to scroll a lot to find a certain highlighted entry! Thanks very much!

**Comment by Klocman** [comment]
I added an F3 search feature, will be available shortly in a new release.

**Comment by SeriousMartin** [comment]
@Klocman Thanks a lot for the new feature and the release. At first glance everything seems to be working fine.

**Comment by Joooki** [comment]
Wow thanks, this will help us and our translators a lot!
