### ISSUE TITLE
Saving reverts order of keys

### ISSUE THREAD

**Issue by SeriousMartin** [HakanL/resxtranslator#35]
Quite strange: When I open a resx file to edit it and save, all the keys are stored in reverse order of what they were like when opened.

You can have a try with the attached file (is renamed to txt because github does not allow uploading resx):
[Test.txt](https://github.com/HakanL/resxtranslator/files/3063063/Test.txt)

Do you have time to work on this soon? Otherwise we will have to revert to the old 2.6 version which lacks the search functionality for now (unfortunately I wont be able to look into this and send a pull request).

**Comment by Klocman** [comment]
It was my mess-up, sorry! I forgot to merge my search feature branch with master with your fixes, and I built the release using that.

I [posted a fixed release](https://github.com/HakanL/resxtranslator/releases/tag/v2.8), I tested and confirmed it's fixed

**Comment by SeriousMartin** [comment]
@Klocman Wow, that was really quick. Thanks a lot!
