### ISSUE TITLE
Build 26.02.2018 - Error compiling

### ISSUE THREAD

**Issue by bovirus** [HakanL/resxtranslator#45]
@Klocman

Running latest source code I got this errors

1>------ Build started: Project: PortableSettingsProvider, Configuration: Debug Any CPU ------
1>  PortableSettingsProvider -> j:\Development\VisualC\resxtranslator-master\bin\Debug\PortableSettingsProvider.dll
2>------ Build started: Project: ResxTranslator, Configuration: Debug Any CPU ------
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "DotNetZip, Version=1.12.0.0, Culture=neutral, PublicKeyToken=6583c7c814667745, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "ScintillaNET, Version=3.6.3.0, Culture=neutral, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2>j:\Development\VisualC\resxtranslator-master\src\Windows\MainWindow.cs(11,7,11,12): error CS0246: The type or namespace name 'Ionic' could not be found (are you missing a using directive or an assembly reference?)
2>j:\Development\VisualC\resxtranslator-master\src\Windows\CellEditorWindow.cs(4,7,4,19): error CS0246: The type or namespace name 'ScintillaNET' could not be found (are you missing a using directive or an assembly reference?)
2>j:\Development\VisualC\resxtranslator-master\src\Windows\CellEditorWindow.Designer.cs(116,18,116,30): error CS0246: The type or namespace name 'ScintillaNET' could not be found (are you missing a using directive or an assembly reference?)
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by bovirus** [comment]
When you make a new build could you pelase everytime compile it and make a new relase available here

https://github.com/HakanL/resxtranslator/releases

Thanks.

**Comment by Klocman** [comment]
Did you manage to compile the source in the end? The errors look like you need to either right click Solution > Restore nuget packages, or clone a fresh copy of the repository and try again. 

If you managed to compile the source please close this issue, thanks!

**Comment by bovirus** [comment]
OK: Fixed. Please close the issue.
