### ISSUE TITLE
About windows - Strings untranslated

### ISSUE THREAD

**Issue by bovirus** [HakanL/resxtranslator#46]
The About window contains elements untranslated.
If you can please add this items in language file to enable translation

![About](https://user-images.githubusercontent.com/1262554/75456899-6941f080-597b-11ea-87b4-344ad129d7b3.jpg)

Please check items with red border.

**Comment by Klocman** [comment]
The strings are now properly translated. The description box needs a new translation, for now it's untranslated.

**Comment by bovirus** [comment]
@Klocman 

Now version could **_2.9.xxxx.x.xxx_**

Copyright Hakan Lindestaf **_2010_** for me could be **2020**

Now in the About box there is a **_Company name:_** without the name of company

![image](https://user-images.githubusercontent.com/1262554/75611415-9b3d8900-5b1a-11ea-9f21-497ccc3e1631.png)

**Comment by Klocman** [comment]
Version and copyright are correct. I added company name string.

**Comment by bovirus** [comment]
The latest version of April 2019 was 2.8.
To highlight that is a new version could be useful to change it to 2.9.xx.

For the same reason copyright 2010 about you when the latest changes are 2020 could be changed to Copyright Hakan Lindestaf 2020 (someone could be read as software of 2010...).
.

**Comment by Klocman** [comment]
2.8 is the "pretty" version number that is user accessible and used in listings. The real version number that is displayed here is used to see which build exactly you are using. There can be many different builds of a single version. This full version number is also visible in file properties of `ResxTranslator.exe`.

The copyright date should always be the date of the first publication/release. https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated

**Comment by bovirus** [comment]
All software that I always seen include always in the copyright year th year of of last changes.

Because the copyright is always referred to the property of the code and if the code is changed in 2020 the copyright have to follow the changes.

If you get for example **_Adobe Reader_** it report as **_Copyright 1984-2020_** (first release - latest release) that is common form.

**Comment by Klocman** [comment]
While it's true that a copyright range can be added, it doesn't have any legal purpose since the copyright is counted from the first date to until after the author's death. It can be added to make it look better but then it has to be kept up to date.
