### ISSUE TITLE
About box issue

### ISSUE THREAD

**Issue by bovirus** [HakanL/resxtranslator#47]
@Klocman

Now version could **_2.9.xxxx.x.xxx_**

Copyright Hakan Lindestaf **_2010_** for me could be **_2020_**

Now in the About box there is a **Company name:** without the name of company

![image](https://user-images.githubusercontent.com/1262554/75611590-1bb0b980-5b1c-11ea-8627-a689587572d0.png)

**Comment by Klocman** [comment]
Duplicate of #46
