### ISSUE TITLE
[PlaceholderText] error in it/es language file

### ISSUE THREAD

**Issue by bovirus** [HakanL/resxtranslator#48]
IOpen with RexTranslator the source tree of resxtranslator it show an errior (marked in red) about [PlaceholderText] 

![image](https://user-images.githubusercontent.com/1262554/75611608-3e42d280-5b1c-11ea-870a-83623db9db89.png)

but I didn't ssee any error (both string es and it are available).

**Comment by Klocman** [comment]
Text inside [ ] brackets is always treated as if it's untranslated. In this case the text is simply not used and can be ignored. Either leave it untranslated or put in an empty string.

**Comment by bovirus** [comment]
@Klocman 

If the text is not used/important why don't change from

**_[Placeholdertext]_** to **_(PlaceholderText)_**

In this way you can avoid this cosmetic error that is not an error.

**Comment by Klocman** [comment]
This text is pasted in the editor when adding a new row and is supposed to be highlighted to show that you didn't fill in the translation yet. It's the same reason why it's highlighted for you, so this should be ignored.

**Comment by bovirus** [comment]
@Klocman 

Personally I didn't view negative poibnt to chnage to (PlaceholderText),

When you add a new string you see it always as new string in any case.

**Comment by Klocman** [comment]
There is no point in simply removing this feature, some people might rely on it in their workflows.

**Comment by bovirus** [comment]
OK: Thanks.
Please close this ticket.
