### ISSUE TITLE
Spanish translation strings missing

### ISSUE THREAD

**Issue by bovirus** [HakanL/resxtranslator#49]
@HakanL 

Who are in charge about Spanish (es) translation?

This is the es current status

Control\LanguageSettings.xml - 4 strings
Properties\Resources.xml - file missing
Resources\Localization - 8 strings
Windows\AboutBox.xml - 3 strings
Windows\CellEditorWindow - 1 string
Windows\MainWindow.xml - 11 strings

**Comment by Klocman** [comment]
@Xelwon is the original creator of the Spanish translation.

**Comment by bovirus** [comment]
@Xelwon 

Could you please if you can update your Spanish language?

**Comment by bovirus** [comment]
@HakanL 

If now the Spanish translation is complete for all modules I think that you can close this issue.

Thanks.
