### ISSUE TITLE
Run two times source code compilation (creation src/packages folder)

### ISSUE THREAD

**Issue by bovirus** [HakanL/resxtranslator#52]
@HakanL 

Is it normal that everyy time form scratch (downlaod zip clone of the repository and decompress it) I have run two times the source code compilation with Visual C 2017?

The first time the compiler report an error that are missing the package

DotNetZip
Scintilla.NET

but create the src/packages folder with the new package. DotNetZip/Scintilla.NET

Then the second time that I run compilation of source code teh compiler found DotNet/Scintilla.NET package and compile the source code without error.

Thanks.

**Comment by Klocman** [comment]
Rebuilding the solution for the first time should automatically create this folder and download dependencies. If that doesn't happen you can right click the solution and then `Restore nuget packages`. This is how it's supposed to work, if you had issues with compiling then it was most likely an issue with your environment, for example bad file permissions. Running visual studio as administrator can sometimes help with those issues.

**Comment by bovirus** [comment]
Thanks for the clarification.
