### ISSUE TITLE
New release with commits after 03.03.2020

### ISSUE THREAD

**Issue by bovirus** [HakanL/resxtranslator#59]
@HakanL 

Could you please make a new version taking all commits after 03.03.2020 (date of latest relase)??

**Comment by HakanL** [comment]
@bovirus Thanks for the request. @Klocman is more or less spearheading this project, I'm sure he will build a new release shortly.

**Comment by Klocman** [comment]
Done https://github.com/HakanL/resxtranslator/releases/tag/v2.10
