### ISSUE TITLE
Unexpected "Missing resource file" dialog pops up on the Missing translations tab

### ISSUE THREAD

**Issue by apuchkov** [HakanL/resxtranslator#61]
If I go to the Missing translations, then click on the resource I'm getting the "Missing resource file" dialog every time:
![image](https://user-images.githubusercontent.com/150003/116255439-3ee6f100-a740-11eb-98c5-08dbcadda4d8.png)

Not sure if it is something wrong with my resx files or bug in the app.
Here are my files with just a few strings to show this issue:
[Accounts resx files.zip](https://github.com/HakanL/resxtranslator/files/6385181/Accounts.resx.files.zip)

I'm using version 2.10 of the app downloaded from Github.

**Comment by Klocman** [comment]
This should be fixed in v2.11. Please reopen the issue if the problem persists.
