### ISSUE TITLE
Missing translation area also shows fully translated resources

### ISSUE THREAD

**Issue by apuchkov** [HakanL/resxtranslator#62]
Hello,

We have ~100 different resx files in the solution. 

I'm planning to give Resx Resource Translation to the translator so she can add translations to newly added resources.

I was hoping that Missing translations tab would only show resources with missing translations or at least highlight them in red. That would help translator to find a few resource files where translations need to be added instead of checking all 100 resource files. Currently, it shows all resources for me, all in black.

Is it a missing functionality or a bug?

![image](https://user-images.githubusercontent.com/150003/116257445-0f38e880-a742-11eb-8fd7-d70a8ef3b70a.png)

Attached a few simplified files to reproduce this issue. Accounts has missing translations. Address is fully translated
[Accounts and addresses resxs.zip](https://github.com/HakanL/resxtranslator/files/6385245/Accounts.and.addresses.resxs.zip)

Thanks!

**Comment by HakanL** [comment]
Hello, sorry about the late response. I'm not very active in this project any more, but if you have a PR for this issue then I'm happy to review and accept.

**Comment by Klocman** [comment]
It was caused by the lowercase language codes in the filenames.
