### ISSUE TITLE
Find window - GUI fix and improvent

### ISSUE THREAD

**Issue by bovirus** [HakanL/resxtranslator#64]
@HakanL 

Please fix this GUI issues

![image](https://user-images.githubusercontent.com/1262554/169768962-5bce2770-67c2-4cf1-8c54-b3f0489d832e.png)

Plase increase text width explained.
Please mowe "Whole word " on right to have enough space for other string "Controlla maiuscole/minuscole" on the left

Please change "Find all" in "Find".

Please add if you can an option to search text in "original" or "translated" strings

If no text was found show a window "No text found".

**Comment by Klocman** [comment]
Fixed in https://github.com/HakanL/resxtranslator/commit/01dd44054cd20f102eee6ac8dfd23805cb257510
