### ISSUE TITLE
Request for improvement - Set default language to view in settings

### ISSUE THREAD

**Issue by bovirus** [HakanL/resxtranslator#66]
@HakanL 
@Klocman 

When I open a folder with language files to have jyts teh langaueg useful for me (master + italian), if teh fodler contains several languages I have everytime to deselct all languages except master and my language.

Could be possible to add in in program settings an option to select the default language flags to enable (master always included).

In my case i world to enable only "it" language.

**Comment by HakanL** [comment]
Can you add a screenshot or two that shows the issues?

**Comment by bovirus** [comment]
@HakanL 

![image](https://user-images.githubusercontent.com/1262554/170109636-975297d4-f0a2-464d-860f-bf9f5fa64290.png)

Open with ResXtranslator Bulk CrapUninstalelr.
it contains several langauges.
16 langauges.
then 17 language columns (16 + master)
To see only master and italian I ahve to deselect manually 15 languages.
And opening it next time I have to do that again.

propsoal n. 1
"Select all" tab header can works as "select all"/"descelect all".
in thsi way I can clic "Seelct alL" (used as Descelt all" and then click only oj i.t

Poproasl n.2
Add in the application settings an option to select what are the languages showed by default (in my case only "it").
